---
branches:
  only:
  - master

os: osx
language: generic

env:
  global:
    - TARGET=localhost
    - CONNECTION=local
    - PYTHONPATH="/Library/Python/2.7/site-packages:$PYTHONPATH"
  matrix:
    - REPOSITORY="default"
    - REPOSITORY="custom"

# This role needs sudo, thus we can't use the new container infrastructure
# sudo: false
sudo: required

install:
  - sudo pip install -U setuptools
  - sudo pip install ansible
  # Resolve dependencies(When target role isn't installed via Ansible Galaxy, auto resolution of dependencies doesn't occur.)
  - ansible-galaxy install FGtatsuro.python-requirements

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - if [ "${REPOSITORY}" == "default" ]; then ansible-playbook tests/test.yml -i tests/inventory -l ${TARGET} --connection=${CONNECTION} -vvvv; fi
  - if [ "${REPOSITORY}" == "custom" ]; then ansible-playbook tests/test.yml -i tests/inventory -l ${TARGET} --connection=${CONNECTION} --extra-vars="intellij_homebrew_repository=FGtatsuro/homebrew-custom intellij_homebrew_formula=intellij-idea-ce15" -vvvv; fi
  - gem update bundler
  - bundle install
  - if [ "${REPOSITORY}" == "default" ]; then bundle exec rake spec SPEC_TARGET=${TARGET}; fi
  - if [ "${REPOSITORY}" == "custom" ]; then bundle exec rake spec SPEC_TARGET=${TARGET} INTELLIJ_HOMEBREW_FORMULA=intellij-idea-ce15; fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
